#
# Copyright IBM Corp, SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  alice.sdk.openapi.demo.com:
    container_name: alice.sdk.openapi.demo.com
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/specs/openapi-${ALICE_API_HOST}.yml
      - BASE_URL=/openapi
    ports:
      - 8089:8080
    volumes:
      - ./specs:/specs
    networks:
      - agent-sdk-rest-net

  bob.sdk.openapi.demo.com:
    container_name: bob.sdk.openapi.demo.com
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/specs/openapi-${BOB_API_HOST}.yml
      - BASE_URL=/openapi
    ports:
      - 9089:8080
    volumes:
      - ./specs:/specs
    networks:
      - agent-sdk-rest-net

  carl.sdk.openapi.demo.com:
    container_name: carl.sdk.openapi.demo.com
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/specs/openapi-${CARL_API_HOST}.yml
      - BASE_URL=/openapi
    ports:
      - 10089:8080
    volumes:
      - ./specs:/specs
    networks:
      - agent-sdk-rest-net

  carl.router.sdk.openapi.demo.com:
    container_name: carl.router.sdk.openapi.demo.com
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/specs/openapi-${CARL_ROUTER_API_HOST}.yml
      - BASE_URL=/openapi
    ports:
      - 10099:8080
    volumes:
      - ./specs:/specs
    networks:
      - agent-sdk-rest-net

  dave.sdk.openapi.demo.com:
    container_name: dave.sdk.openapi.demo.com
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/specs/openapi-${DAVE_API_HOST}.yml
      - BASE_URL=/openapi
    ports:
      - 10069:8080
    volumes:
      - ./specs:/specs
    networks:
      - agent-sdk-rest-net

  dave.router.sdk.openapi.demo.com:
    container_name: dave.router.sdk.openapi.demo.com
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/specs/openapi-${DAVE_ROUTER_API_HOST}.yml
      - BASE_URL=/openapi
    ports:
      - 10079:8080
    volumes:
      - ./specs:/specs
    networks:
      - agent-sdk-rest-net

networks:
  agent-sdk-rest-net:
    external: true