# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - master
pr:
  - master
variables:
  GO_VERSION: 1.15
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: Checks
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          echo '//npm.pkg.github.com/:_authToken=${DOCKER_PASSWORD}' > ~/.npmrc
          echo '@hyperledger:registry=https://npm.pkg.github.com' >> ~/.npmrc
          echo '@trustbloc-cicd:registry=https://npm.pkg.github.com' >> ~/.npmrc
          make checks
        env:
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
        displayName: Run checks
  - job: UnitTest
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make unit-test
        displayName: Run unit test
      - script: bash <(curl https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN
        env:
          CODECOV_UPLOAD_TOKEN: $(CODECOV_UPLOAD_TOKEN)
        displayName: Upload coverage to Codecov

  - job: UnitTestWasm
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make unit-test-wasm
        displayName: Run unit test wasm
  - job: Publish
    dependsOn:
      - Checks
      - UnitTest
      - UnitTestWasm
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          source ci/version_var.sh
          cd ./cmd/agent-js-worker
          echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' > ~/.npmrc
          echo '@hyperledger:registry=https://npm.pkg.github.com' >> ~/.npmrc
          echo '@trustbloc-cicd:registry=https://npm.pkg.github.com' >> ~/.npmrc
          sed -i 's/"version": "0.1.0"/"version": "'$NPM_PKG_TAG'"/g' package.json
          sed -i 's#"name": "@trustbloc/agent-sdk"#"name": "@'${NPM_PKG_NAME}'"#g' package.json
          sed -i 's#"url": "git://github.com/trustbloc/agent-sdk.git"#"url": "git://github.com/'${NPM_PKG_REPO}'.git"#g' package.json
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: $(DOCKER_PASSWORD)
          NPM_PKG_TAG: $(NPM_PKG_TAG)
          NPM_PKG_NAME: $(NPM_PKG_NAME)
          NPM_PKG_REPO: $(NPM_PKG_REPO)
